Issue/logout action
zmora-agh/zmora-ui pull request #113
Opened 2017-05-09 20:00 UTC by marcskow

2017-05-09 20:43 UTC, marcskow commented
Jeżeli chodzi o to jak klient reaguje na odpowiedź zwrotną od serwera to zrozumiałem to tylko w połowniczym stopniu ale na tyle żeby móc wpłynąć na zmianę stanu za pomocą reducer'a, nie wiem tylko jak wywołać przy okazji odpowiednią akcję, tzn:

PROBLEM:
- RifghtMenu jest otwarte gdy:  open && logged
- Open na początku = false, i nie mamy możliwości wysunięcia bo nie jesteśmy zalogowani.
- Po zalogowaniu nadal open: false, ale mamy możliwość wysunięcia
- Robimy toggle więc open = true && logged = true więc się wysuwa
- Wylogowujemy, więc logged = false więc się zamyka
- Ponownie się logujemy więc logged = true ale open zapamiętane również = true więc się automatycznie wysuwa (a domyślnie po zalogowaniu chcemy mieć zamknięte chyba nadal).

Jak to rozwiązać? Mogę przy wylogowaniu wykonać jakąś akcję która mi zmieni open na false?

2017-05-10 18:29 UTC, marcskow commented
Problem opisany w poprzednim komentarzu naprawiony. Mati powiedział mi trochę o akcjach na zmiane propsów i poczytałem o lifecycle obiektów. Użyłem componentWillReceiveProps

2017-05-16 20:06 UTC, maxmati requested changes

2017-05-16 20:06 UTC, maxmati commented on app/components/AppToolbar/index.js
> +          onClick={() => this.context.router.push('/auth')}
1. nie powinniśmy się dobierać do routera tak na chama, tylko zrobić `dispatch` akcji `push`
2. ścieżki nie powinny być hardkodowane tylko mamy taki plik `local-urls.js` z ich generatorami

2017-05-16 20:06 UTC, maxmati commented on app/components/AppToolbar/index.js
> +  generateIconPanel() {
zamiast funkcji zrobił bym zwykły komponent

2017-05-16 20:06 UTC, maxmati commented on app/components/AppToolbar/index.js
> +    router: React.PropTypes.object.isRequired,
nie powinniśmy się tak dobierać do routera jeżeli nie jest to konieczne

2017-05-16 20:06 UTC, maxmati commented on app/components/AppToolbar/messages.js
> +    id: 'app.components.AppToolbar.loginButtonText',
id dwóch wiadomości nie może się pokrywać (patrz linijka 14)

2017-05-16 20:06 UTC, maxmati commented on app/containers/App/index.js
> +    return this.props.logged && this.state.rightMenuOpen;
zamiast sprawdzać tutaj czy user jest zalogowany to sprawdzałbym to w funkcji `toggleMenu` ponieważ teraz jeżeli wylogowany user zrobi toggleMenu po czym się zaloguje to menu mu się wysunie

2017-05-16 20:06 UTC, maxmati commented on app/containers/App/reducer.js
> +        logged: true,
nie jestem pewien czy osobna flaga logged to jest dobry pomysł ponieważ to jest kolejne pole które trzeba utrzymywać. Wydaje mi się że lepszym pomysłem jest decydowanie w selektorze czy user jest zalogowany na podstawie obiektu `user`. I nie wiem czy nie istnieje gdzieś już jakaś funkcja do sprawdzania czy user nie jest zalogowany.

2017-07-09 20:07 UTC, marcmos commented
W tym momencie jest dług techniczny na 70 commitów i w najbliższym czasie raczej się nic nie zmieni. @marcskow, gdybyś coś z tym zrobił, otwórz ten PR z powrotem.

2017-07-09 20:07 UTC, closed without merging