Redirect to not found page on contest not found
zmora-agh/zmora-ui pull request #184
Opened 2017-08-12 15:50 UTC by maxmati

Part of #180

2017-08-12 15:54 UTC, marcmos requested changes
Nie testowałem jeszcze całości.

2017-08-12 15:54 UTC, marcmos commented on app/containers/ProblemsPage/index.js
> +@loadable({ display: 'blokc', found: (p) => p.data.contest !== null })
`block`.

2017-08-12 15:57 UTC, maxmati commented on app/containers/ProblemsPage/index.js
> +@loadable({ display: 'blokc', found: (p) => p.data.contest !== null })
done

2017-08-14 19:51 UTC, marcmos approved these changes

2017-08-14 19:52 UTC, merged