Add contest participants page
zmora-agh/zmora-ui pull request #217
Opened 2017-09-23 20:00 UTC by marcmos

Requires back-end change zmora-agh/zmora-server-rails#67.

2017-09-23 21:44 UTC, oszust002 requested changes

2017-09-23 21:44 UTC, oszust002 commented on app/components/ContestParticipants/index.js
> +export const participationsPropTypes =
Wyniósłbym to do constants.js

2017-09-23 21:44 UTC, oszust002 commented on app/containers/ContestParticipantsPage/index.js
> +  if (props.data.loading || props.data.error) return null;
Czemu w ten sposób? Nie chcemy ładowania strony w przypadku loading? A w przypadku error też powinniśmy chyba coś wyświetlić ( @maxmati nie dodawałeś czegoś do wyświetlania w razie błędów?).

2017-09-23 21:44 UTC, oszust002 commented on app/containers/ContestPage/messages.js
> +    id: 'app.containers.ContestPage.empty',
Czemu wyniosłeś to do ContestPage? ContestPage w tej chwili jedyne co robi to przekierowuje do listy problemów.

2017-09-23 22:36 UTC, maxmati commented on app/containers/ContestParticipantsPage/index.js
> +  if (props.data.loading || props.data.error) return null;
Pisałem tylko do błędów krytycznych.
Ale do ładowania jest https://github.com/zmora-agh/zmora-ui/blob/e2c64210a03238fd8cc82b9d4bff8b53075628f9/app/utils/render.js#L18 może można też rozszerzyć o obsługę błędów.

2017-09-24 19:55 UTC, oszust002 approved these changes

2017-09-24 20:01 UTC, merged