Update about page informations
zmora-agh/zmora-ui pull request #223
Opened 2017-09-27 18:30 UTC by oszust002

Part of #166

2017-09-27 20:11 UTC, maxmati requested changes
What do you think about trying to align height of `MemberAvatar` height?

2017-09-27 20:17 UTC, marcmos requested changes
Wykadruj i wyskaluj do jednej rozdzielczości nasze zdjęcia.

2017-10-01 16:59 UTC, marcmos approved these changes

2017-10-10 11:04 UTC, maxmati approved these changes

2017-10-10 11:14 UTC, merged